name: Construir contenedor de la aplicación

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Construir crt del servidor
        run: echo ${{ secrets.B64_CERT }} | base64 --decode > src/main/resources/local-ssl.p12
        working-directory: micro-gestion-usuarios

      - name: Construir con Maven
        run: mvn clean package
        working-directory: micro-gestion-usuarios

      - name: Construir contenedor Docker
        run: docker build -t micro-gestion-usuarios .
        working-directory: micro-gestion-usuarios

      - name: Obtener la fecha actual
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
        working-directory: micro-gestion-usuarios

      - name: Etiquetar contenedor Docker
        run: |
          docker tag micro-gestion-usuarios ghcr.io/forte-gestorjobs/micro-gestion-usuarios:${{ steps.get_date.outputs.date }}
          docker tag micro-gestion-usuarios ghcr.io/forte-gestorjobs/micro-gestion-usuarios:latest
        working-directory: micro-gestion-usuarios

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir contenedor Docker a GHCR 
        run: |
          docker push ghcr.io/forte-gestorjobs/micro-gestion-usuarios:${{ steps.get_date.outputs.date }}
          docker push ghcr.io/forte-gestorjobs/micro-gestion-usuarios:latest
        working-directory: micro-gestion-usuarios
